### ISSUE TITLE
Time to release the code. 

### ISSUE THREAD

**Issue by JingyuLi-code** [JacobYuan7/RLIP#1]
Hi, this is a good work！When will the complete code be published？

**Comment by JacobYuan7** [comment]
> Hi, this is a good work！When will the complete code be published？

Hi, I am actually uploading the annotations and checkpoints. You can get access to them whenever the uploading process is finished. With regard to the code, we encountered a technical issue during the pre-release review. So, you may need to wait for more time (1-2 weeks hopefully). Sorry about the delay.

**Comment by JacobYuan7** [comment]
The code is out. So, I closed the issue.
