### ISSUE TITLE
zero-shot settings questions

### ISSUE THREAD

**Issue by hangzhiyiwei** [JacobYuan7/RLIP#5]
Hi, @JacobYuan7,  thank you for your excellent work.

I have some questions about the zero-shot settings. I found that in the RFUC/ NFUC training annotation files, those images with unseen HOI classes are also included in the training. I just wonder what is the definition of the zero-shot settings. Only the HOI annotations are masked but all the images are available? 

In this case, how can you use those images without annotations for training? I saw that those images' annotations are all set to 0. If so, will those images hurt the training?

Thank you very much.

**Comment by JacobYuan7** [comment]
@hangzhiyiwei  
Many thanks for your interest in this work. 

Generally speaking, I believe it is acceptable to include all training images as long as we do not access the unseen annotations, as defined by [FCL](https://openaccess.thecvf.com/content/CVPR2021/html/Hou_Detecting_Human-Object_Interaction_via_Fabricated_Compositional_Learning_CVPR_2021_paper.html) and [VCL](https://link.springer.com/chapter/10.1007/978-3-030-58555-6_35).

Currently, I do not employ any specific techniques for handling images without annotations. Moreover, I have not compared the performance differences between including and excluding these images. I presume incorporating them might degrade the performance, as it would introduce negative labels into the training process.

**Comment by hangzhiyiwei** [comment]
I understand it. Thanks a lot for your reply.

**Comment by JacobYuan7** [comment]
@hangzhiyiwei  Feel free to ask more. By now, I am closing this issue as completed.
