### ISSUE TITLE
something about the VG dataset?

### ISSUE THREAD

**Issue by xiaomabufei** [JacobYuan7/RLIP#6]
hello! There are some problems with the dataset link (VG) you provided. Could you please share the dataset you used for pre-training?
![031d8dff10e8b713e43c9f50b2defa0](https://user-images.githubusercontent.com/104605826/235571982-0afe032a-3979-4d8c-afc3-eb086f0d9592.png)

**Comment by JacobYuan7** [comment]
@xiaomabufei 
Do you mean that you can not get access to [this link](https://zjueducn-my.sharepoint.com/personal/hj_yuan_zju_edu_cn/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fhj%5Fyuan%5Fzju%5Fedu%5Fcn%2FDocuments%2FPublic%2FNeurIPS22%5FPublic%5FRLIP%5FCode%5FAnnotations%5Fand%5FCheckpoints%2Fannotations%2Fannotations%2Fscene%5Fgraphs%5Fpreprocessv1%2Ezip&parent=%2Fpersonal%2Fhj%5Fyuan%5Fzju%5Fedu%5Fcn%2FDocuments%2FPublic%2FNeurIPS22%5FPublic%5FRLIP%5FCode%5FAnnotations%5Fand%5FCheckpoints%2Fannotations%2Fannotations&ga=1)?

It seems that I can get access to the link by Google Chrome, Microsoft Edge and even my self-phone. Can you try other browsers or other laptops to download it? If you still fail, I can try to share it with you by other means.

**Comment by JacobYuan7** [comment]
@xiaomabufei 
Hi, it seems that the official link is no longer available. I have provided new ones in the github repo. You can use my link. The number of images should be the same as what I claimed in the paper.

(Note: If the official website is not working, you can use the link that I provide: [Images](https://zjueducn-my.sharepoint.com/:u:/g/personal/hj_yuan_zju_edu_cn/Ed38rTcxgq9JnMdQS0SUSAIBE2azKnbq8_ZosJ6RZHaJjg?e=bpeuLt) and [Images2](https://zjueducn-my.sharepoint.com/:u:/g/personal/hj_yuan_zju_edu_cn/Ea09ejSJ_KpJm_CKmmgMeScB81gSfJXD9gp7INzSrX53mg?e=pPQCo1).)

**Comment by JacobYuan7** [comment]
@xiaomabufei  I closed this issue as completed. Feel free to re-open it if you have further questions.
