### ISSUE TITLE
The link for annotations and weights are expired

### ISSUE THREAD

**Issue by hangzhiyiwei** [JacobYuan7/RLIP#8]
Hi, thanks for your nice work.

I found that the links for the annotations and weights are expired. Could you please update the links? Thanks very much!

**Comment by JacobYuan7** [comment]
@hangzhiyiwei  I am working on it. I find one drive has some rule change about file sharing. I will get it done as soon as possible. I will get you notified if I am done.

**Comment by JacobYuan7** [comment]
@hangzhiyiwei  Hi, I've got it done. Thanks for the reminder.

**Comment by hangzhiyiwei** [comment]
Hi, thanks for your update! It can work now.
